baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vhok74.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging


paginate: 7
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
#tag_permalink_style:  pretty

#Catagories
category_dir: 'category'

category_layout: "index.html"

collections_dir: my_collections
collections:
  computer:
    output: true
  write-up:
    output: true
  security:
    output: true
sass:
  sass_dir: _sass
  style: compressed

future: true