#-------------------------------
# General Site Settings
title: JaHo
logo: logo2.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll

#-------------------------------
# Author Settings
author:
  name: Jaheo Jung
  image: auth2.jpg
  say-hello: <strong>Step by step goes a long way</strong>
  bio: Never give up. Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine. _Jack MaDesigns<br>자호의 평범한 블로그. 컴마스터가 되는 그날 까지
        


#-------------------------------
# Contact links
twitter: https://twitter.com/jungjaeho6 # Add your Twitter handle
facebook: https://www.facebook.com/wogh8732 # Add your Facebook handle
instagram: https://instagram.com/wogh8732 # Add your Instagram handle



#-------------------------------
# Comment Section (Disqus)
disqus-identifier: pwnhub # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
